name: Deploy
on:
  push:
    branches: [main]

jobs:
  Deploy_Front:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Usar Node.js 18.16.0 para fazer o build
      uses: actions/setup-node@v2
      with:
        node-version: 18.16.0
    - run: |
          cd web
          npm install
          CI=false npm run build
    - name: Transferir o build para o servidor
      uses: easingthemes/ssh-deploy@v2.1.4
      env: 
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
        REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
        REMOTE_USER: ${{ secrets.DEPLOY_USER }}
        REMOTE_PORT: ${{ secrets.DEPLOY_PORT }}
        SOURCE: "web/dist/"
        TARGET: ${{ secrets.DEPLOY_FRONT_TARGET }}
  Deploy_Back:
    runs-on: ubuntu-latest
    steps:
    - name: Transferir o projeto para o servidor
      uses: easingthemes/ssh-deploy@v2.1.4
      env: 
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
        REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
        REMOTE_USER: ${{ secrets.DEPLOY_USER }}
        REMOTE_PORT: ${{ secrets.DEPLOY_PORT }}
        SOURCE: "api/"
        TARGET: ${{ secrets.DEPLOY_BACK_TARGET }}
        SCRIPT_AFTER: |
          npm i
          npm run start:prod
