name: Deploy
on:
  push:
    branches: [main]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Usar Node.js 20.x para fazer o build
      uses: actions/setup-node@v2
      with:
        node-version: 20.x
    - run: npm install
    - run: CI=false npm run build
    - name: Transferir o build para o servdor
      uses: easignthemes/ssh-deploy@v2.1.4
      env: 
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
        REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
        REMOTE_USER: ${{ secrets.DEPLOY_USER }}
        REMOTE_PORT: ${{ secrets.DEPLOY_PORT }}
        SOURCE: "build/"
        TARGET: ${{ secrets.DEPLOY_TARGET }}
